### ISSUE TITLE
Download images

### ISSUE THREAD

**Issue by AISLVE** [Pankaj-Meharchandani/Waller#1]
Add an option to download images as well as make the ui just a little better if possible, like making it a bit more round and being able to adjust the noise, still a great app with lots of potential, cheers mate

**Comment by AISLVE** [comment]
Also everytime you rotate the device the walls automatically refresh

**Comment by Pankaj-Meharchandani** [comment]
thanks for the feedback. 👍
will start working on it soon ❤️

**Comment by Pankaj-Meharchandani** [comment]
> And it looks off on tablet ![Screenshot_2024-02-09-01-37-10-912_com example waller](https://private-user-images.githubusercontent.com/121119257/303469668-32816200-e5de-47ee-8222-cac9ec647883.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzAyNzYsIm5iZiI6MTcwODkyOTk3NiwicGF0aCI6Ii8xMjExMTkyNTcvMzAzNDY5NjY4LTMyODE2MjAwLWU1ZGUtNDdlZS04MjIyLWNhYzllYzY0Nzg4My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwNjQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2QyMjlmODY2Mjg2NWJkNTk3NjBmNWQyODA0ZmE1MmQ0YWUyYmEwNTVhN2NiNWY3YTQzNDU1ZDIxNzgyZTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VOgxHD-9rs-CXXffgxYFwLURf33A8AkD2FSoqjKzdgQ) ![Screenshot_2024-02-09-01-37-07-510_com example waller](https://private-user-images.githubusercontent.com/121119257/303469694-a9e9c31c-dd36-474f-92cb-f5142c5cc196.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzAyNzYsIm5iZiI6MTcwODkyOTk3NiwicGF0aCI6Ii8xMjExMTkyNTcvMzAzNDY5Njk0LWE5ZTljMzFjLWRkMzYtNDc0Zi05MmNiLWY1MTQyYzVjYzE5Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwNjQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTFmZjg2ODVjODNjYWFmNWFiOGY4MGQ0MjYzOTc0OTViNDgyOTk4MjhjZWNmZTg5MmRkYzQ4YWE0OTA1ODE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0ojlrZgbizE9KsTYrZsOTxP984OAzyPn3Z1KJrj2ZRE)

as the wallpaper is in potrait mode only, it will look like this only on tab, but i will work to make it atleast look good on tab as well.

**Comment by Pankaj-Meharchandani** [comment]
> Add an option to download images as well as make the ui just a little better if possible, like making it a bit more round and being able to adjust the noise, still a great app with lots of potential, cheers mate

done all the changes possible 👍
thanks mate for your support
